apiVersion: v1
kind: Pod
metadata:
  name: db-pod
  labels:
    app: postgres
    environment: dev
    team: backend
spec:
  containers:
  - name: postgres
    image: postgres:15-alpine
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
