apiVersion: v1
kind: Pod
metadata:
  name: env-configmap-pod
spec:
  containers:
  - name: print-env
    image: busybox
    command: ["sh", "-c", "echo '=== APP CONFIG VARIABLES ===' && env | grep APP_ && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
  restartPolicy: Never
