apiVersion: v1
kind: Pod
metadata:
  name: propagation-pod
spec:
  containers:
  - name: reader
    image: busybox
    command: ["sh", "-c", "while true; do echo \"[$(date)] message: $(cat /etc/live-config/message)\"; sleep 5; done"]
    volumeMounts:
    - name: live-config-vol
      mountPath: /etc/live-config
  volumes:
  - name: live-config-vol
    configMap:
      name: live-config
