# Use the lightweight Nginx Alpine base image
FROM nginx:alpine

# Copy the custom index.html to Nginx's default HTML public folder
COPY index.html /usr/share/nginx/html/index.html

# Expose container HTTP standard port 80
EXPOSE 80
